#!/usr/bin/env sh

DIR=`dirname $0`
PYTHONPATH=${DIR}:${DIR}/lib:${DIR}/plugins
export DIR PYTHONPATH
if [ .$PYTHON = . ]; then
	PYTHON=python
fi
${PYTHON} ${DIR}/configJoy.py $*
#python -m cProfile -o config.out ${DIR}/configJoy.py $*
